version: 2
updates:
  - package-ecosystem: pip
    directory: /projects/verifiable-shuffle
    schedule:
      interval: monthly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      security-patches:
        patterns:
          - "*"
        applies-to: security-updates
  - package-ecosystem: npm
    directory: /projects/verifiable-shuffle-frontend
    schedule:
      interval: monthly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
      security-patches:
        patterns:
          - "*"
        applies-to: security-updates
